*****************************************************************
* SAMPLE BANKING SYSTEM
*****************************************************************

START

LOGIN:
    LOAD R1, CUSTOMER_ID
    LOAD R2, PASSWORD
    CALL AUTHENTICATE
    BNE LOGIN_FAILED
    CALL MAIN_MENU
    BR END_PROGRAM

LOGIN_FAILED:
    DISPLAY "INVALID USER"
    BR END_PROGRAM


TRANSFER:
    LOAD R3, SENDER_ACCOUNT
    LOAD R4, RECEIVER_ACCOUNT
    LOAD R5, AMOUNT

    CALL CHECK_BALANCE
    BNE INSUFFICIENT_FUNDS

    CALL UPDATE_SENDER
    CALL UPDATE_RECEIVER
    CALL SAVE_TRANSACTION

    BR TRANSFER_SUCCESS

INSUFFICIENT_FUNDS:
    DISPLAY "INSUFFICIENT BALANCE"
    BR END_PROGRAM

TRANSFER_SUCCESS:
    DISPLAY "TRANSFER SUCCESSFUL"


CALCULATE_INTEREST:
    LOAD R6, BALANCE
    LOAD R7, RATE
    MULT R6, R7
    STORE INTEREST
    RETURN


GENERATE_REPORT:
    CALL GET_TRANSACTIONS
    CALL PRINT_REPORT
    RETURN


MAIN_MENU:
    DISPLAY "1. Check Balance"
    DISPLAY "2. Transfer Money"
    DISPLAY "3. Generate Report"
    RETURN


AUTHENTICATE:
    LOAD USER_TABLE
    RETURN


CHECK_BALANCE:
    LOAD BALANCE
    COMPARE BALANCE, AMOUNT
    RETURN


UPDATE_SENDER:
    SUB BALANCE, AMOUNT
    STORE BALANCE
    RETURN


UPDATE_RECEIVER:
    ADD BALANCE, AMOUNT
    STORE BALANCE
    RETURN


SAVE_TRANSACTION:
    STORE TRANSACTION_LOG
    RETURN


GET_TRANSACTIONS:
    LOAD TRANSACTION_LOG
    RETURN


PRINT_REPORT:
    DISPLAY "TRANSACTION REPORT"
    RETURN


END_PROGRAM:
    STOP

END